Repository m-lab/etl, pull requests merged in 2018-10, with the labels that each got.

#564 Unconitionally return false for "shouldEmbargo"
  functions/embargo/transfer.js
Labels: Sprint 17, Task, swarm

#568 Update travis.yml to use "master" branch
  .travis.yml
Labels: Sprint 18

#571 Consistent project & dataset names
  .travis.yml
  bq/bq_test.go
  cmd/etl_worker/app-batch.yaml
  cmd/etl_worker/app-disco.yaml
  cmd/etl_worker/app-ndt-prod.yaml
  cmd/etl_worker/app-ndt-staging.yaml
  cmd/etl_worker/app-ndt.yaml
  cmd/etl_worker/app-sidestream.yaml
  cmd/etl_worker/app-traceroute.yaml
  cmd/etl_worker/fast-sidestream.yaml
  etl/globals.go
  etl/globals_test.go
Labels: Sprint 18, Task

#572 Correct typo on INJECTED_PROJECT for sidestream
  .travis.yml
Labels: Sprint 18, Task

#573 Add translation func from gs dir to BQ table name
  etl/globals.go
  etl/globals_test.go
Labels: 1, Sprint 18, Task

#587 Use static metric label for annotator post errors
  annotation/geo.go
Labels: Sprint 19, Task
